DATASET:
  TRAIN: "../../../datasets/coco2017/train2017.txt"
  VAL: "../../../datasets/coco2017/val2017.txt"
  NAMES: "configs/coco_80.names"
MODEL:
  NC: 80
  INPUT_WIDTH: 256
  INPUT_HEIGHT: 256
  SEPARATION: 3
  SEPARATION_SCALE: 2
  REG_MAX: 1
  REG_SCALE: 0.5
TRAIN:
  LR: 0.01
  THRESH: 0.25
  WARMUP: true
  BATCH_SIZE: 96
  END_EPOCH: 300
  MILESTIONES:
    - 100
    - 200
    - 250
  AMP: False
  USE_TAA: True
VAL:
  CONF: 0.001
  NMS: 0.5
  IOU: 0.4