DATASET:
  TRAIN: "../../../datasets/hand_det/train.txt"
  VAL: "../../../datasets/hand_det/val.txt"
  NAMES: "configs/hand.names"
MODEL:
  NC: 19
  INPUT_WIDTH: 192
  INPUT_HEIGHT: 192
  SEPARATION: 3
  SEPARATION_SCALE: 4
  REG_MAX: 1
  REG_SCALE: 0.5
TRAIN:
  LR: 0.1
  THRESH: 0.25
  WARMUP: true
  BATCH_SIZE: 96
  END_EPOCH: 300
  MILESTIONES:
    - 100
    - 200
    - 250
  AMP: False
  USE_TAA: True
VAL:
  CONF: 0.001
  NMS: 0.5
  IOU: 0.4